version: "3"
services:
  api:
    container_name: mrb-api
    build: .
    command: python -m debugpy --listen 0.0.0.0:5678 -m flask run -h 0.0.0.0 -p 8000
    depends_on:
      - db
    ports:
      - 6868:8000
      - 5678:5678
    volumes:
      - .:/code
    env_file:
      - .env
    restart: always
  frontend:
    container_name: mrb-frontend
    build: ./frontend
    depends_on:
      - api
    ports:
      - 3000:3000
    volumes:
      - "./frontend/:/app"
      - "/app/node_modules"
    env_file:
      - .env
    restart: always
  db:
    container_name: mrb-db
    image: postgres:15.0
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: always
