const actions = {
  // Review
  GET_PUBLIC_REVIEW_REQUESTING: "GET_PUBLIC_REVIEW_REQUESTING",
  GET_PUBLIC_REVIEW_SUCCESS: "GET_PUBLIC_REVIEW_SUCCESS",
  GET_PUBLIC_REVIEW_FAILED: "GET_PUBLIC_REVIEW_FAILED",

  GET_USER_REVIEW_REQUESTING: "GET_USER_REVIEW_REQUESTING",
  GET_USER_REVIEW_SUCCESS: "GET_USER_REVIEW_SUCCESS",
  GET_USER_REVIEW_FAILED: "GET_USER_REVIEW_FAILED",

  CREATE_REVIEW_REQUESTING: "CREATE_REVIEW_REQUESTING",
  CREATE_REVIEW_SUCCESS: "CREATE_REVIEW_SUCCESS",
  CREATE_REVIEW_FAILED: "CREATE_REVIEW_FAILED",

  DELETE_REVIEW_REQUESTING: "DELETE_REVIEW_REQUESTING",
  DELETE_REVIEW_SUCCESS: "DELETE_REVIEW_SUCCESS",
  DELETE_REVIEW_FAILED: "DELETE_REVIEW_FAILED",

  // Auth
  SIGN_IN_REQUESTING: "SIGN_IN_REQUESTING",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILED: "SIGN_IN_FAILED",
  SIGN_OUT: "SIGN_OUT",

  SIGN_UP_REQUESTING: "SIGN_UP_REQUESTING",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILED: "SIGN_UP_FAILED",

  // Folder
  GET_FOLDER_REQUESTING: "GET_FOLDER_REQUESTING",
  GET_FOLDER_SUCCESS: "GET_FOLDER_SUCCESS",
  GET_FOLDER_FAILED: "GET_FOLDER_FAILED",

  CREATE_FOLDER_REQUESTING: "CREATE_FOLDER_REQUESTING",
  CREATE_FOLDER_SUCCESS: "CREATE_FOLDER_SUCCESS",
  CREATE_FOLDER_FAILED: "CREATE_FOLDER_FAILED",
};

export default actions;
