from http import HTTPStatus

INTERNAL_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR, "INTERNAL_ERROR"
USER_ALREADY_EXIST = HTTPStatus.BAD_REQUEST, "USER_ALREADY_EXIST"
AUTHENTICATION_FAILED = HTTPStatus.UNAUTHORIZED, "AUTHENTICATION_FAILED"
AUTHORIZATION_HEADER_REQUIRED = HTTPStatus.UNAUTHORIZED, "AUTHORIZATION_HEADER_REQUIRED"
TOKEN_REQUIRED = HTTPStatus.UNAUTHORIZED, "TOKEN_REQUIRED"
INVALID_TOKEN = HTTPStatus.UNAUTHORIZED, "INVALID_TOKEN"
TOKEN_EXPIRED = HTTPStatus.UNAUTHORIZED, "TOKEN_EXPIRED"
FOLDER_ALREADY_EXIST = HTTPStatus.BAD_REQUEST, "FOLDER_ALREADY_EXIST"
FOLDER_NOT_FOUND = HTTPStatus.NOT_FOUND, "FOLDER_NOT_FOUND"
